### ISSUE TITLE
Chrome failed to start

### ISSUE THREAD

**Issue by estivalet** [solairen/docker_robotframework#16]
When trying to run the image the following error is displayed:

docker run -it --rm -v ${PWD}:/robot moleszek/robotframework:latest -m robot test.robot

I think the image is using root to launch chrome. Is there a way to change this behaviour?

WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x563df9ccfa23 <unknown>
#1 0x563df979ae18 <unknown>
#2 0x563df97be1f1 <unknown>
#3 0x563df97b991a <unknown>
#4 0x563df97f474a <unknown>
#5 0x563df97ee883 <unknown>
#6 0x563df97c43fa <unknown>
#7 0x563df97c54c5 <unknown>
#8 0x563df9cff16d <unknown>
#9 0x563df9d155bb <unknown>
#10 0x563df9d00e75 <unknown>
#11 0x563df9d15e85 <unknown>
#12 0x563df9cf486f <unknown>
#13 0x563df9d30ae8 <unknown>
#14 0x563df9d30c68 <unknown>
#15 0x563df9d4baad <unknown>
#16 0x7f0fc85d8ea7 <unknown>

**Comment by solairen** [comment]
Hi @estivalet 

Thank you for creating this issue.

In this case, the root is not a problem to run chrome.

Inside the **Keywords** section you need to create a step that will run chrome in headless mode.

```robot
Chrome Headless
    ${chrome_options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
    Call Method    ${chrome_options}    add_argument    --disable-extensions
    Call Method    ${chrome_options}    add_argument    --headless
    Call Method    ${chrome_options}    add_argument    --disable-gpu
    Call Method    ${chrome_options}    add_argument    --no-sandbox
    Create Webdriver    Chrome    chrome_options=${chrome_options}
```

Then in **Settings** add **Test Setup** and run **Chrome Headless**.

See this [example](https://github.com/solairen/docker_robotframework/blob/main/tests/example.robot) how it's should look like.

Please, let me know if this solution is good for you 😄

**Comment by estivalet** [comment]
Hi @solairen thanks for the reply. Yes it works. But in this case I am not able to see the browser running the test. I am doing my personal docker image with VNC just for testing purporses and I don't know how I can run chrome with non-root user.

**Comment by solairen** [comment]
@estivalet 

If you want to add a user to your docker image just add it to Dockerfile:
```Dockerfile
(...)
ARG user={USERNAME}
ARG home=/home/${user}
RUN addgroup docker
RUN adduser --disabled-password --gecos "" --home ${home} --ingroup docker ${user}

RUN chown ${user}:docker /usr/bin/google-chrome
RUN chown $[user}:docker /usr/bin/chromedriver
```

Then you will need to do this (depends on your os system): [dockerGUI](https://cuneyt.aliustaoglu.biz/en/running-gui-applications-in-docker-on-windows-linux-mac-hosts/)

Lastly, you will need to modify  this:
```robot
*** Keywords ***
Chrome Headless
    ${chrome_options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
    Call Method    ${chrome_options}    add_argument    --disable-extensions
    Call Method    ${chrome_options}    add_argument    --headless
    Call Method    ${chrome_options}    add_argument    --disable-gpu
    Call Method    ${chrome_options}    add_argument    --no-sandbox
    Create Webdriver    Chrome    chrome_options=${chrome_options}
```

to that:
```robot
*** Keywords ***
Chrome Headless
    ${chrome_options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
    Call Method    ${chrome_options}    add_argument    --disable-extensions
    Call Method    ${chrome_options}    add_argument    --no-sandbox
    Create Webdriver    Chrome    chrome_options=${chrome_options}
```

You will see the browser running as a non-root user inside your docker container.

**Comment by estivalet** [comment]
@solairen Thanks for the help! I'll give a try.
